server.port: 8082

spring:
  application.name: accountservice
  security:
    user:
      name: xiaoming
      password: 123456

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tianyalan: INFO

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always