server:
  port: 8082

spring:
  application.name: accountservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointment?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=GMT
    username: root
    password: 123456

logging:
  level:
    com.tianyalan: INFO

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always